#!/bin/bash

REP_ROOT=/home/eis/ligue-score/

BACKEND_FOLDER=$REP_ROOT/backend/
BACKEND_SCRIPT_FOLDER=$BACKEND_FOLDER/scripts

TARGET_BUILD_ROOT=$BACKEND_FOLDER/build/

TARGET_PUBLISH_ROOT=/var/www/html


FRONTEND_FOLDER=$REP_ROOT/frontend/league-front/
FRONTEND_TARGET_BUILD_ROOT=$FRONTEND_FOLDER/dist/league-front/